name: Check for Test Files

on:
  pull_request:
    branches:
      - main  # Change to your default branch if it's different

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check for Test Files
        run: |
          if [ -z "$(find . -name '*test*.js')" ]; then
            echo "No test files found. Please add a test file before submitting the PR."
            exit 1
          fi
